name: Lint 🎳

on:
  push:
#    paths:
#      - '**.py'
  pull_request:
#    paths:
#      - '**.py'

jobs:
  test-flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: x64
          cache: "pip"
          cache-dependency-path: "requirements/dev.txt"

      - name: Install Python requirements
        run: pip install -r requirements/dev.txt

      - name: Run flake8
        run: flake8
